### ISSUE TITLE
Can't logout when running AfL on Zorin 15

### ISSUE THREAD

**Issue by digidave777** [cross-platform/audible-for-linux#10]
Thanks for building this app - I look forward to using it!
I have 2 Audible accounts (one for audible.co.uk, one for audible.com) and I logged into the wrong one. I can't now logout as the only screen I can see is the Library and I have no books in this account. Any advice how I can logout, please?

**Comment by MarcusTomlinson** [comment]
If you've logged into .com and would like to switch to .co.uk, edit the file:

`~/snap/audible-for-linux/common/locale`

and replace "US" with "GB"

**Comment by MarcusTomlinson** [comment]
A shortcut to this is to open a terminal and run:

`echo "GB" > ~/snap/audible-for-linux/common/locale`

**Comment by digidave777** [comment]
Many thanks - when I changed the locale it asked me to login again.
