### ISSUE TITLE
Today's update caused a break on linux

### ISSUE THREAD

**Issue by sachio222** [cross-platform/audible-for-linux#12]
v 0.4.0 latest/stable won't load today. 

Not sure if there was a breaking change. 

1. Start app.
2.  Click on listen now anywhere
3. play-window pops up
4. Buffering overlay shows. 
5. Hangs for 15-20 seconds
6. error popup shows with text: An error occurred during processing. Please close this window and try again later. 

OS: ElementaryOS

P.S. The app worked fine yesterday

**Comment by kwazzi-jack** [comment]
Can confirm this exact same break happens for me. Running v0.4.0 latest/stable on Ubuntu 20.04.

**Comment by MarcusTomlinson** [comment]
Yeah, I can confirm this too. In fact playback appears to have broken in Firefox as well.

**Comment by MarcusTomlinson** [comment]
Ok, this should now be fixed in version 0.5.0 of the snap. Please run `snap refresh audible-for-linux`

**Comment by sachio222** [comment]
Working like a charm. Thank you!
