### ISSUE TITLE
failing to start due to not finding libxshmfence shared library

### ISSUE THREAD

**Issue by arronhuk** [cross-platform/audible-for-linux#13]
not very familiar with snap but this was working and after the upgrade of pop_os to 21.04 from 20.10

snap/audible-for-linux/13/audible-for-linux: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory

**Comment by arronhuk** [comment]
complete deletion and re-install fixed the issue

**Comment by MarcusTomlinson** [comment]
Thanks for the update.
