### ISSUE TITLE
Region Lock

### ISSUE THREAD

**Issue by smokecatcher** [cross-platform/audible-for-linux#14]
I am a US citizen living in the UK. I have both US and UK audible books, but I can't use your app to listen to them because there is no way for me to change my sign in to the audible.com rather than the audible.co.uk --- audible allows this -- so you should too.

**Comment by MarcusTomlinson** [comment]
You can select the appropriate store via the following steps: https://github.com/cross-platform/audible-for-linux/issues/2#issuecomment-687783318
