### ISSUE TITLE
Configure appUrl and signUrl instead of using getLocaleCountryCode

### ISSUE THREAD

**Issue by sspross** [cross-platform/audible-for-linux#2]
Hi, thanks for your work. Is there a way to configure the `appUrl` and `signUrl` or the `localeCountryCode` which should be used? Because my systems is set to `EN` and I'm a customer of de German Audible store.

Thank you very much and best regards,
Silvan

**Comment by MarcusTomlinson** [comment]
This is now possible via version 0.3.0 of the snap.

Override your locale in `~/snap/audible-for-linux/common/locale`

For example:
```
mkdir -p ~/snap/audible-for-linux/common
echo "DE" > ~/snap/audible-for-linux/common/locale
```

Available locales:

```
CA - Canada
GB - United Kingdom
IE - Ireland
AU - Australia
NZ - New Zealand
FR - France
DE - Germany
JP - Japan
IN - India
```

Anything else will direct you to the standard .com store.

**Comment by daviswr23** [comment]
Thank you - MarcusTomlinson

experiencing the issue in reverse I could only access the '.co.uk' site.
- Even though I'm in Ireland my content is in the '.com' site.
- Even with VPN & Location set to USA

So using reverse logic I used:

> **mkdir -p ~/snap/audible-for-linux/common**
> **echo "US" > ~/snap/audible-for-linux/common/locale**

Worked brilliantly for me.
