### ISSUE TITLE
blank page on ubuntu

### ISSUE THREAD

**Issue by fpusersuggest** [cross-platform/audible-for-linux#5]
Hello, I have ubuntu 20.04 and I installed audible-for-linux from snapstore. But after I logon on audible what I see is a blank page.

**Comment by MarcusTomlinson** [comment]
Thanks for the report @fpusersuggest.

What’s probably happened here is the app has detected the incorrect store locale for you.

Could you please try manually selecting the appropriate store with the following steps: https://github.com/cross-platform/audible-for-linux/issues/2#issuecomment-687783318

**Comment by fpusersuggest** [comment]
I didn't change the locale because it's right.
Also I tried with wireshark and the store is correct.

**Comment by fpusersuggest** [comment]
I have tried other locale like: GB DE FR IN and they work. The only one that doesn't work is IT.

**Comment by fpusersuggest** [comment]
Hello, I discovered that in the italian website there is not the "library", it's pretty weird because on the button close the the podcast there is written "add to library". I contacted the customer service and they have confirmed that to see the library I have to download the app. I have the same problems with an other linux software for audible. Then I think you should remove the compatibility for italian locale.

**Comment by MarcusTomlinson** [comment]
Ah I see, ok, thanks for the info @fpusersuggest!
