### ISSUE TITLE
Blank page after Audible login

### ISSUE THREAD

**Issue by sid-biciuz** [cross-platform/audible-for-linux#7]
Blank page after Audible login on Linux Mint 20

**Comment by MarcusTomlinson** [comment]
Thanks for the report @sid-biciuz

What’s possibly happened here is the app has detected the incorrect store locale for you.

Could you please try manually selecting the appropriate store with the following steps: https://github.com/cross-platform/audible-for-linux/issues/2#issuecomment-687783318
