### ISSUE TITLE
Does not lauch properly after installation

### ISSUE THREAD

**Issue by jontrossbach** [cross-platform/audible-for-linux#8]
Hi, I just installed version 0.3.0 (latest/stable) via the Ubuntu Software Center on Ubuntu 18.05.4 LTS x86_64. It will not launch the app from the shortcut. Is this version of Ubuntu supposed to be supported?

Is there a way to try and run it from the command line?

**Comment by MarcusTomlinson** [comment]
Hi, yeah it definitely should launch. Could you open the Terminal, run: `audible-for-linux`, and share the output here.

**Comment by jontrossbach** [comment]
Hi Marcus, 

Glad to be in touch. Glad to know I wasn't over thinking it, too. My output can be summarized as the following:

`~$ audible-for-linux`
`~$` 

It is installed though:

`~$ which audible-for-linux`
`/snap/bin/audible-for-linux`

If I run it as root (probably not intended):

`# audible-for-linux`
`mkdir: cannot create directory '/run/user/0': Permission denied`

**Comment by MarcusTomlinson** [comment]
Oh, no output at all, that's super weird. Could you try a complete reinstall like so:

```
snap remove --purge audible-for-linux
rm -rf ~/snap/audible-for-linux
snap install audible-for-linux
```

Then run `audible-for-linux` from the terminal again and share the output.

**Comment by jontrossbach** [comment]
```
/snap/bin$ snap remove --purge audible-for-linux
audible-for-linux removed
/snap/bin$ rm -rf ~/snap/audible-for-linux
/snap/bin$ snap install audible-for-linux
audible-for-linux 0.3.0 from Marcus Tomlinson (marcustomlinson) installed
/snap/bin$ audible-for-linux
/snap/bin$
```

**Comment by MarcusTomlinson** [comment]
Hmm ok, could you open a second terminal and run `journalctl -f`, then run `audible-for-linux` in the first terminal again and share the output from the journal.

**Comment by jontrossbach** [comment]
```
t1:
~$ journalctl -f
.
.
.
Dec 13 03:39:52 jon-Precision-5530 audit[12487]: AVC apparmor="DENIED" operation="open" profile="snap.audible-for-linux.audible-for-linux" name="/home/jon/Documents/" pid=12487 comm="head" requested_mask="r" denied_mask="r" fsuid=1001 ouid=1001
Dec 13 03:39:52 jon-Precision-5530 kernel: audit: type=1400 audit(1607848792.251:505): apparmor="DENIED" operation="open" profile="snap.audible-for-linux.audible-for-linux" name="/home/jon/Documents/" pid=12487 comm="head" requested_mask="r" denied_mask="r" fsuid=1001 ouid=1001

t2:
~$ audible-for-linux
```

**Comment by MarcusTomlinson** [comment]
Ok, could you try the version in candidate like so:

```
snap remove --purge audible-for-linux
rm -rf ~/snap/audible-for-linux
snap install audible-for-linux --candidate
```

Then run `audible-for-linux` from the terminal again and share the output.

**Comment by jontrossbach** [comment]
Hey! That worked.

Small detail that might be worth looking into is that if I accidentally double-click the shortcut two instances are started. Other snap packages only allow one instance to launch even with a double click. It is working now though.

**Comment by MarcusTomlinson** [comment]
Excellent! Thanks for the update.
